name: Bug report
description: Report bugs with the engine here
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your bug here."
    validations:
      required: true
      
  - type: textarea
    id: terminal
    attributes:
      label: "Command Prompt/Terminal/Crash logs (if existing)"
      placeholder: "None"
    validations:
      required: false

  - type: textarea
    id: reproduce
    attributes:
      label: "Describe the steps on how to occur this bug/crash."
    validations:
      required: false