name: Help me!
description: If you need help using the engine.
labels: [help wanted]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your problem here."
    validations:
      required: true
